from __future__ import annotations

from typing import Protocol

from kb.note.model import Note


class NoteStorePort(Protocol):
    def read(self, path: str, logical_path: str | None = None) -> Note: ...
    def write(self, note: Note, path: str | None = None) -> None: ...
    def read_text(self, path: str) -> str: ...
    def write_text(self, path: str, text: str) -> None: ...
    def exists(self, path: str) -> bool: ...
    def remove(self, path: str) -> None: ...
    def prune(self, paths: tuple[str, ...]) -> None: ...
    def files(self) -> tuple[str, ...]: ...
    def directories(self) -> tuple[str, ...]: ...
    def paths(self) -> tuple[str, ...]: ...


class SearchIndexPort(Protocol):
    def upsert(self, note: Note, vector: object) -> None: ...
    def set_payload(self, point_id: str, fields: dict[str, object]) -> None: ...
    def search(self, vector: object, filters: dict[str, object], *,
               include_history: bool = False, include_legacy: bool = False) -> object: ...
    def mark_legacy(self, prefix: str, *, source_paths: tuple[str, ...] | None = None) -> int: ...


class EmbedderPort(Protocol):
    def embed(self, text: str) -> object: ...


class TranscriptSourcePort(Protocol):
    def load(self, path: str) -> str: ...


class ClockPort(Protocol):
    def now(self) -> str: ...
